'use client';

import {Check, Pencil, Search, ShieldCheck, UserRoundPlus, X} from 'lucide-react';
import {FormEvent, useState} from 'react';

export type TeamOperator = {id: string; email: string; fullName: string; role: TeamRole; status: TeamStatus; createdAt: string};
type TeamRole = 'admin' | 'staff' | 'graphic_operator';
type TeamStatus = 'active' | 'suspended' | 'revoked';
const roleLabels: Record<TeamRole, string> = {admin: 'Amministrazione', staff: 'Account Manager', graphic_operator: 'Grafico'};
const statusLabels: Record<TeamStatus, string> = {active: 'Attivo', suspended: 'Sospeso', revoked: 'Revocato'};

export function AdminTeamDirectory({initialOperators}: {initialOperators: TeamOperator[]}) {
  const [operators, setOperators] = useState(initialOperators);
  const [query, setQuery] = useState('');
  const [isCreating, setIsCreating] = useState(false);
  const [editingOperator, setEditingOperator] = useState<TeamOperator | null>(null);
  const [error, setError] = useState('');
  const visibleOperators = operators.filter((operator) => !query.trim() || [operator.fullName, operator.email, roleLabels[operator.role]].some((value) => value.toLocaleLowerCase('it-IT').includes(query.trim().toLocaleLowerCase('it-IT'))));
  return <><section className="team-toolbar"><div><span className="eyebrow">AMMINISTRAZIONE</span><h2>Team & ruoli</h2><p>Gestisci gli accessi del team interno: Amministrazione, Account Manager e Grafico.</p></div><button className="button button--primary" onClick={() => setIsCreating(true)} type="button"><UserRoundPlus size={17} />Nuovo operatore</button></section>{error ? <p className="directory-error">{error}</p> : null}
    <section className="team-directory"><div className="team-directory__filters"><label className="client-search"><Search size={17} /><input onChange={(event) => setQuery(event.target.value)} placeholder="Cerca operatore o email..." value={query} /></label></div><div className="team-directory__head"><span>Operatore</span><span>Email</span><span>Ruolo</span><span>Stato</span><span>Azioni</span></div>{visibleOperators.map((operator) => <article className="team-directory__row" key={operator.id}><strong>{operator.fullName}</strong><span>{operator.email}</span><span className={`team-role team-role--${operator.role}`}>{roleLabels[operator.role]}</span><span className={`team-status team-status--${operator.status}`}>{statusLabels[operator.status]}</span><button className="client-action" onClick={() => setEditingOperator(operator)} type="button"><Pencil size={15} />Modifica</button></article>)}{!visibleOperators.length ? <p className="client-list__empty">Nessun operatore corrisponde alla ricerca.</p> : null}</section>
    {isCreating ? <OperatorModal mode="create" onClose={() => setIsCreating(false)} onError={setError} onSaved={(operator) => { setOperators((current) => [operator, ...current]); setIsCreating(false); }} /> : null}
    {editingOperator ? <OperatorModal mode="edit" operator={editingOperator} onClose={() => setEditingOperator(null)} onError={setError} onSaved={(operator) => { setOperators((current) => current.map((item) => item.id === operator.id ? operator : item)); setEditingOperator(null); }} /> : null}
  </>;
}

function OperatorModal({mode, onClose, onError, onSaved, operator}: {mode: 'create' | 'edit'; onClose: () => void; onError: (error: string) => void; onSaved: (operator: TeamOperator) => void; operator?: TeamOperator}) {
  const [error, setError] = useState(''); const [isSaving, setIsSaving] = useState(false);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); onError(''); setIsSaving(true); const form = new FormData(event.currentTarget); const payload = {fullName: String(form.get('fullName') || ''), email: String(form.get('email') || ''), role: String(form.get('role') || ''), status: String(form.get('status') || '')}; try { const response = await fetch(mode === 'create' ? '/api/admin/team' : `/api/admin/team/${operator?.id}`, {method: mode === 'create' ? 'POST' : 'PATCH', headers: {'Content-Type': 'application/json'}, body: JSON.stringify(mode === 'create' ? {fullName: payload.fullName, email: payload.email, role: payload.role} : {fullName: payload.fullName, role: payload.role, status: payload.status})}); const result = await readResponse(response); if (!response.ok || !result.operator) throw new Error(result.error || 'Salvataggio non riuscito.'); onSaved(toOperator(result.operator)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Salvataggio non riuscito.'); } finally { setIsSaving(false); } }
  return <div aria-modal="true" className="modal-backdrop" role="dialog"><section className="client-modal"><header><div><h2>{mode === 'create' ? 'Nuovo operatore' : 'Modifica operatore'}</h2><p>{mode === 'create' ? 'Verrà inviata un’email per impostare una password personale.' : operator?.email}</p></div><button aria-label="Chiudi" className="modal-close" onClick={onClose} type="button"><X size={19} /></button></header><form className="client-form" onSubmit={save}><label className="client-form__wide">Nome e cognome<input defaultValue={operator?.fullName || ''} name="fullName" required /></label><label className="client-form__wide">Email<input defaultValue={operator?.email || ''} disabled={mode === 'edit'} name="email" required type="email" /></label><label>Ruolo<select defaultValue={operator?.role || 'staff'} name="role">{Object.entries(roleLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{mode === 'edit' ? <label>Stato<select defaultValue={operator?.status || 'active'} name="status">{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label> : <p className="team-modal-hint"><ShieldCheck size={17} />Il ruolo determina automaticamente l’interfaccia dopo il login.</p>}{error ? <p className="form-error">{error}</p> : null}<footer className="modal-actions"><button className="client-action" disabled={isSaving} onClick={onClose} type="button">Annulla</button><button className="client-action client-action--primary" disabled={isSaving} type="submit"><Check size={16} />{isSaving ? 'Salvataggio...' : mode === 'create' ? 'Invia invito' : 'Salva modifiche'}</button></footer></form></section></div>;
}

function toOperator(value: {id: string; email: string; full_name: string | null; role: TeamRole; status: TeamStatus; created_at: string}): TeamOperator { return {id: value.id, email: value.email, fullName: value.full_name || value.email, role: value.role, status: value.status, createdAt: value.created_at}; }
async function readResponse(response: Response) { const contentType = response.headers.get('content-type') || ''; if (contentType.includes('application/json')) return await response.json() as {error?: string; operator?: {id: string; email: string; full_name: string | null; role: TeamRole; status: TeamStatus; created_at: string}}; return {error: response.ok ? 'Risposta non valida dal server.' : 'Il servizio non è disponibile. Riprova tra qualche istante.'}; }
